import { useMemo } from 'react';

export const mockCartItems: ICart = {
  id: "1",
  user_id: "2",
  cartItems: [
    {
      id: 1,
      product_id: "1",
      cart_id: 1,
      quantity: 1,
      product: {
        id: 'skin1004',
        createdAt: '2025-01-01T10:00:00Z',
        updatedAt: '2025-01-02T12:00:00Z',
        productCategory: { title: 'Sunscreen', description: "" },
        productBrand: { title: 'Skin1004', description: "" },
        title: 'Skin1004 Sunscreen for Sensitive Skin SPF 50+ 50ml',
        description: 'A lightweight, non-greasy sunscreen designed for sensitive skin with SPF 50+ protection.',
        price: 465000,
        sale_price: 242000,
        image_url: 'https://picsum.photos/1000',
        product_category_id: 1,
        product_brand_id: 1,
        total_stock: 100,
        created_at: '2025-01-01T10:00:00Z',
        updated_at: '2025-01-02T12:00:00Z',
        ingredients: 'Zinc Oxide, Titanium Dioxide, Niacinamide',
        how_to_use: 'Apply generously to face and neck 15 minutes before sun exposure.',
        rating: 4.5,
        reviews_count: 120,
      },
    },
    {
      id: 2,
      product_id: "2",
      cart_id: 1,
      quantity: 2,
      product: {
        id: 'cosrx123',
        createdAt: '2025-02-01T09:30:00Z',
        updatedAt: '2025-02-02T10:45:00Z',
        productCategory: { title: 'Cleanser', description: "" },
        productBrand: { title: 'COSRX', description: "" },
        title: 'COSRX Low pH Good Morning Gel Cleanser 150ml',
        description: 'Gentle gel cleanser with tea tree oil and low pH formula to cleanse without stripping skin.',
        price: 230000,
        sale_price: 190000,
        image_url: 'https://picsum.photos/1001',
        product_category_id: 2,
        product_brand_id: 2,
        total_stock: 80,
        created_at: '2025-02-01T09:30:00Z',
        updated_at: '2025-02-02T10:45:00Z',
        ingredients: 'Tea Tree Oil, Betaine Salicylate, Allantoin',
        how_to_use: 'Massage gently on wet skin and rinse thoroughly.',
        rating: 4.7,
        reviews_count: 305,
      },
    },
    {
      id: 3,
      product_id: "3",
      cart_id: 1,
      quantity: 1,
      product: {
        id: 'in203',
        createdAt: '2025-03-10T14:20:00Z',
        updatedAt: '2025-03-11T16:00:00Z',
        productCategory: { title: 'Serum', description: "" },
        productBrand: { title: 'The Inkey List', description: "" },
        title: 'The Inkey List Niacinamide Serum 30ml',
        description: 'Helps reduce excess oil, blemishes, and redness with 10% niacinamide.',
        price: 310000,
        sale_price: 295000,
        image_url: 'https://picsum.photos/1002',
        product_category_id: 3,
        product_brand_id: 3,
        total_stock: 60,
        created_at: '2025-03-10T14:20:00Z',
        updated_at: '2025-03-11T16:00:00Z',
        ingredients: 'Niacinamide 10%, Hyaluronic Acid',
        how_to_use: 'Apply a pea-sized amount to cleansed face in the morning and evening.',
        rating: 4.3,
        reviews_count: 90,
      },
    },
    {
      id: 4,
      product_id: "4",
      cart_id: 1,
      quantity: 1,
      product: {
        id: 'klairs456',
        createdAt: '2025-04-05T08:15:00Z',
        updatedAt: '2025-04-06T09:00:00Z',
        productCategory: { title: 'Toner', description: "" },
        productBrand: { title: 'Klairs', description: "" },
        title: 'Klairs Supple Preparation Unscented Toner 180ml',
        description: 'A soothing, hydrating toner without essential oils—perfect for sensitive skin.',
        price: 320000,
        sale_price: 289000,
        image_url: 'https://picsum.photos/1003',
        product_category_id: 4,
        product_brand_id: 4,
        total_stock: 70,
        created_at: '2025-04-05T08:15:00Z',
        updated_at: '2025-04-06T09:00:00Z',
        ingredients: 'Beta-Glucan, Hyaluronic Acid, Centella Asiatica Extract',
        how_to_use: 'Apply with hands or cotton pad after cleansing.',
        rating: 4.8,
        reviews_count: 260,
      },
    },
    {
      id: 5,
      product_id: 5,
      cart_id: 1,
      quantity: 3,
      product: {
        id: 'abib789',
        createdAt: '2025-05-15T11:00:00Z',
        updatedAt: '2025-05-16T13:30:00Z',
        productCategory: { title: 'Sheet Mask', description: "" },
        productBrand: { title: 'Abib', description: "" },
        title: 'Abib Mild Acidic pH Sheet Mask - Heartleaf Fit',
        description: 'Soothing mask that helps balance pH and calm sensitive skin.',
        price: 39000,
        sale_price: 30000,
        image_url: 'https://picsum.photos/1004',
        product_category_id: 5,
        product_brand_id: 5,
        total_stock: 300,
        created_at: '2025-05-15T11:00:00Z',
        updated_at: '2025-05-16T13:30:00Z',
        ingredients: 'Heartleaf Extract, Centella Asiatica, Panthenol',
        how_to_use: 'Apply on clean skin, leave for 15-20 mins, remove and pat in essence.',
        rating: 4.6,
        reviews_count: 150,
      },
    },
  ],
};


export const useCart = () => {
    const items = mockCartItems;
    const subtotal = useMemo(() => items.reduce((sum, item) => sum + item.sale_price * item.quantity, 0), [items]);
    return { items, subtotal };
};

