export const sampleProducts = [
  {
    id: 1,
    name: "Hydrating Serum",
    description: "Advanced hydrating serum with hyaluronic acid",
    price: 89.99,
    brand: "The Ordinary",
    category: "Skincare",
    stock: 150,
    images: ["/placeholder.svg?height=100&width=100"],
    discount: 0,
  },
  {
    id: 2,
    name: "Matte Lipstick",
    description: "Long-lasting matte lipstick in vibrant colors",
    price: 24.99,
    brand: "MAC",
    category: "Makeup",
    stock: 200,
    images: ["/placeholder.svg?height=100&width=100"],
    discount: 15,
  },
  {
    id: 3,
    name: "Anti-Aging Cream",
    description: "Premium anti-aging cream with retinol",
    price: 129.99,
    brand: "Estée Lauder",
    category: "Skincare",
    stock: 75,
    images: ["/placeholder.svg?height=100&width=100"],
    discount: 0,
  },
  {
    id: 4,
    name: "Volumizing Shampoo",
    description: "Professional volumizing shampoo for fine hair",
    price: 34.99,
    brand: "L'Oréal",
    category: "Haircare",
    stock: 120,
    images: ["/placeholder.svg?height=100&width=100"],
    discount: 10,
  },
  {
    id: 5,
    name: "Eau de Parfum",
    description: "Elegant floral fragrance for women",
    price: 89.99,
    brand: "Dior",
    category: "Fragrance",
    stock: 60,
    images: ["/placeholder.svg?height=100&width=100"],
    discount: 0,
  },
];
