export const npcProfiles: NPCProfile[] = [
  {
    id: 1,
    name: "Lana",
    avatar_url_default: "https://i.ibb.co/Z6v2B3dQ/lana.png",
    avatar_url_happy: "/avatars/lana_happy.png",
    avatar_url_sad: "/avatars/lana_sad.png",
    concern_line:
      "Hi, I’ve been breaking out lately, especially around my chin.",
    happy_line: "Wow, my skin feels so much clearer! Thank you!",
    unhappy_line: "Ugh, I think the products made it worse...",
    thanks_line: "Thanks for your help! I'll come back if it works well.",
    steps: 4,
    description: "A university student stressed by exams and mask acne.",
    case: {
      caseName: "Acne-prone",
      skinType: "acne-prone",
      tooltip: "Breakouts, inflammation, and clogged pores",
      requiredIngredients: ["Salicylic acid", "Niacinamide", "Tea Tree"],
      avoidIngredients: ["Coconut oil", "Fragrance"],
      requiredProducts: [
        "oil-based-cleanser",
        "gel/foam cleanser",
        "toner",
        "serum",
      ],
      avoidProducts: ["exfoliator", "heavy moisturizer"],
    },
  },
  {
    id: 2,
    name: "Tobias",
    avatar_url_default: "https://i.ibb.co/1JwDC6Kp/tobias.png",
    avatar_url_happy: "/avatars/tobias_happy.png",
    avatar_url_sad: "/avatars/tobias_sad.png",
    concern_line: "My face is always shiny, especially in the T-zone.",
    happy_line: "This is the best my skin has felt in months!",
    unhappy_line: "Still oily. I don’t think the routine helped.",
    thanks_line: "Fingers crossed this helps. Thanks for the advice!",
    steps: 5,
    description: "A bike messenger dealing with oily skin and urban pollution.",
    case: {
      caseName: "Oily skin",
      skinType: "oily",
      tooltip: "Shiny skin due to excess sebum",
      requiredIngredients: ["Clay", "Niacinamide", "Salicylic acid"],
      avoidIngredients: ["Mineral oil", "Petrolatum"],
      requiredProducts: [
        "oil-based-cleanser",
        "gel/foam cleanser",
        "toner",
        "moisturizer",
        "serum",
      ],
      avoidProducts: ["heavy moisturizer", "occlusive balm"],
    },
  },
  {
    id: 3,
    name: "Mei",
    avatar_url_default: "https://i.ibb.co/yBQf1sT9/mei.png",
    avatar_url_happy: "/avatars/mei_happy.png",
    avatar_url_sad: "/avatars/mei_sad.png",
    concern_line: "My cheeks are dry and flaky, especially after cleansing.",
    happy_line: "So much better! My skin actually feels hydrated now.",
    unhappy_line: "Still dry. Maybe I need something more moisturizing?",
    thanks_line: "I appreciate the effort. Let’s see how it goes.",
    steps: 5,
    description:
      "A kindergarten teacher with dry skin from long days in air conditioning.",
    case: {
      skinType: "dry",
      caseName: "Dry skin",
      tooltip: "Flaky, tight skin lacking moisture",
      requiredIngredients: ["Hyaluronic acid", "Ceramides", "Glycerin"],
      avoidIngredients: ["Alcohol", "Benzoyl peroxide"],
      requiredProducts: ["moisturizer", "serum"],
    },
  },
];

export const gameProducts: GameProduct[] = [
  // --- CLEANSERS ---
  {
    id: 1,
    type: "gel/foam-cleanser",
    name: "ClearStart Acne Gel Cleanser",
    image_url: "/products/clearstart_cleanser.png",
    ingredients: ["Salicylic acid", "Tea Tree", "Aloe Vera"],
    tooltip: "Deeply cleanses acne-prone skin while soothing inflammation.",
  },
  {
    id: 2,
    type: "gel/foam-cleanser",
    name: "HydraFoam Gentle Wash",
    image_url: "/products/hydrafoam_cleanser.png",
    ingredients: ["Glycerin", "Hyaluronic acid", "Chamomile"],
    tooltip: "Mild cleanser ideal for dry or sensitive skin types.",
  },
  {
    id: 3,
    type: "gel/foam-cleanser",
    name: "Oil Away Daily Cleanser",
    image_url: "/products/oilfree_cleanser.png",
    ingredients: ["Salicylic acid", "Niacinamide"],
    tooltip: "Controls oil production and clears pores without over-drying.",
  },
  {
    id: 4,
    type: "gel/foam-cleanser",
    name: "Milky Barrier Cleanser",
    image_url: "/products/milky_cleanser.png",
    ingredients: ["Ceramides", "Coconut oil", "Shea Butter"],
    tooltip:
      "Nourishing formula for extreme dryness (not for acne-prone skin).",
  },
  {
    id: 5,
    type: "gel/foam-cleanser",
    name: "Clarifying Gel Wash",
    image_url: "/products/clarifying_cleanser.png",
    ingredients: ["Clay", "Zinc", "Green Tea"],
    tooltip: "Cleanses oily skin and unclogs pores.",
  },

  {
    id: 26,
    type: "oil-based-cleanser",
    name: "Calm & Clean Cleansing Oil",
    image_url: "/products/calm_clean_oil.png",
    ingredients: ["Jojoba Oil", "Chamomile", "Vitamin E"],
    tooltip:
      "Gentle cleansing oil that melts away makeup while calming sensitive skin.",
  },
  {
    id: 27,
    type: "oil-based-cleanser",
    name: "Deep Melt Cleansing Balm",
    image_url: "/products/deepmelt_balm.png",
    ingredients: ["Sunflower Oil", "Green Tea", "Shea Butter"],
    tooltip:
      "Solid balm-to-oil formula that removes impurities without stripping moisture.",
  },
  {
    id: 28,
    type: "oil-based-cleanser",
    name: "Purity First Oil Cleanser",
    image_url: "/products/purity_oil_cleanser.png",
    ingredients: ["Grapeseed Oil", "Tea Tree", "Squalane"],
    tooltip:
      "Lightweight oil that deeply cleanses pores and helps control acne.",
  },
  {
    id: 29,
    type: "oil-based-cleanser",
    name: "Silky Barrier Oil Wash",
    image_url: "/products/silky_oil_cleanser.png",
    ingredients: ["Squalane", "Ceramides", "Avocado Oil"],
    tooltip:
      "Protects skin barrier while effectively lifting off sunscreen and debris.",
  },
  {
    id: 30,
    type: "oil-based-cleanser",
    name: "HydraGlow Cleansing Oil",
    image_url: "/products/hydraglow_oil.png",
    ingredients: ["Argan Oil", "Vitamin C", "Glycerin"],
    tooltip:
      "Brightening oil cleanser that removes dullness and hydrates as it cleanses.",
  },

  // --- TONERS ---
  {
    id: 6,
    type: "toner",
    name: "Refreshing T-Zone Toner",
    image_url: "/products/refresh_toner.png",
    ingredients: ["Witch Hazel", "Salicylic acid", "Niacinamide"],
    tooltip: "Ideal for oily skin, especially in the T-zone.",
  },
  {
    id: 7,
    type: "toner",
    name: "Alcohol-Free Rose Toner",
    image_url: "/products/rose_toner.png",
    ingredients: ["Rose Water", "Glycerin", "Aloe Vera"],
    tooltip: "Hydrating and calming for dry or sensitive skin.",
  },
  {
    id: 8,
    type: "toner",
    name: "Balancing Pore Control Toner",
    image_url: "/products/pore_control_toner.png",
    ingredients: ["Tea Tree", "Clay", "Zinc"],
    tooltip: "Minimizes pores and controls shine for oily/acne skin.",
  },
  {
    id: 9,
    type: "toner",
    name: "Brightening AHA Toner",
    image_url: "/products/aha_toner.png",
    ingredients: ["Lactic Acid", "Glycolic Acid", "Niacinamide"],
    tooltip: "Gentle exfoliation with hydration boost.",
  },
  {
    id: 10,
    type: "toner",
    name: "Fragrance-Free Hydrating Toner",
    image_url: "/products/hydrating_toner.png",
    ingredients: ["Hyaluronic acid", "Ceramides", "Panthenol"],
    tooltip: "Hydrating toner safe for dry and sensitive skin.",
  },

  // --- SERUMS ---
  {
    id: 11,
    type: "serum",
    name: "Blemish Control Serum",
    image_url: "/products/blemish_serum.png",
    ingredients: ["Salicylic acid", "Niacinamide", "Zinc"],
    tooltip: "Targeted treatment for acne and breakouts.",
  },
  {
    id: 12,
    type: "serum",
    name: "HydraBoost Serum",
    image_url: "/products/hydraboost_serum.png",
    ingredients: ["Hyaluronic acid", "Glycerin", "Panthenol"],
    tooltip: "Delivers deep hydration for dry skin types.",
  },
  {
    id: 13,
    type: "serum",
    name: "Pore Minimizing Serum",
    image_url: "/products/poremin_serum.png",
    ingredients: ["Niacinamide", "Green Tea", "Tea Tree"],
    tooltip: "Reduces pores and oiliness for a matte finish.",
  },
  {
    id: 14,
    type: "serum",
    name: "Soothing Repair Serum",
    image_url: "/products/soothing_serum.png",
    ingredients: ["Centella Asiatica", "Ceramides", "Allantoin"],
    tooltip: "Repairs barrier damage and calms sensitive skin.",
  },
  {
    id: 15,
    type: "serum",
    name: "Clarify+ Serum",
    image_url: "/products/clarify_serum.png",
    ingredients: ["Willow Bark", "Clay", "Niacinamide"],
    tooltip: "Ideal for oily and acne-prone skin, reduces congestion.",
  },

  // --- MOISTURIZERS ---
  {
    id: 16,
    type: "moisturizer",
    name: "Matte Balance Gel Cream",
    image_url: "/products/matte_moisturizer.png",
    ingredients: ["Niacinamide", "Green Tea", "Zinc"],
    tooltip: "Controls oil while keeping skin hydrated.",
  },
  {
    id: 17,
    type: "moisturizer",
    name: "Deep Repair Moisturizer",
    image_url: "/products/deeprepair_moisturizer.png",
    ingredients: ["Ceramides", "Hyaluronic acid", "Glycerin"],
    tooltip: "Rich hydration for dry and damaged skin.",
  },
  {
    id: 18,
    type: "moisturizer",
    name: "Lightweight Daily Cream",
    image_url: "/products/lightweight_moisturizer.png",
    ingredients: ["Squalane", "Niacinamide", "Aloe Vera"],
    tooltip: "Non-comedogenic moisturizer for all skin types.",
  },
  {
    id: 19,
    type: "moisturizer",
    name: "Barrier Repair Night Cream",
    image_url: "/products/nightcream_moisturizer.png",
    ingredients: ["Ceramides", "Shea Butter", "Panthenol"],
    tooltip: "Nourishing night cream to repair the skin barrier.",
  },
  {
    id: 20,
    type: "moisturizer",
    name: "Anti-Shine Moisturizer",
    image_url: "/products/shinefree_moisturizer.png",
    ingredients: ["Clay", "Niacinamide", "Tea Tree"],
    tooltip: "Best for oily skin needing hydration without grease.",
  },

  // --- EXFOLIATORS ---
  {
    id: 21,
    type: "exfoliator",
    name: "Gentle Enzyme Peel",
    image_url: "/products/enzyme_peel.png",
    ingredients: ["Papaya Enzymes", "Lactic Acid", "Glycerin"],
    tooltip: "Non-abrasive exfoliation for dry or sensitive skin.",
  },
  {
    id: 22,
    type: "exfoliator",
    name: "Pore Clearing Scrub",
    image_url: "/products/pore_scrub.png",
    ingredients: ["Salicylic acid", "Walnut Shell", "Menthol"],
    tooltip: "Physically and chemically clears out pores.",
  },
  {
    id: 23,
    type: "exfoliator",
    name: "AHA Exfoliating Gel",
    image_url: "/products/aha_exfoliator.png",
    ingredients: ["Glycolic Acid", "Niacinamide", "Panthenol"],
    tooltip: "Smooths skin texture and improves glow.",
  },
  {
    id: 24,
    type: "exfoliator",
    name: "Charcoal Detox Exfoliant",
    image_url: "/products/charcoal_exfoliator.png",
    ingredients: ["Charcoal", "Clay", "Salicylic acid"],
    tooltip: "Ideal for oily and acne-prone skin.",
  },
  {
    id: 25,
    type: "exfoliator",
    name: "Brightening Scrub Mask",
    image_url: "/products/bright_scrub.png",
    ingredients: ["Vitamin C", "Niacinamide", "Rice Powder"],
    tooltip: "2-in-1 mask and scrub for dull skin.",
  },
];

export const skinCases: SkinCase[] = [
  {
    caseName: "Acne-prone",
    tooltip: "Skin with frequent breakouts, inflammation, and oiliness.",
    requiredIngredients: ["Salicylic Acid", "Niacinamide", "Tea Tree Oil"],
    avoidIngredients: ["Coconut Oil", "Lanolin"],
    requiredProducts: ["Cleanser", "Toner"],
    avoidProducts: ["Heavy Creams", "Oil Serums"],
  },
  {
    caseName: "Dry Skin",
    tooltip: "Skin that feels tight, flaky, or rough due to lack of moisture.",
    requiredIngredients: ["Hyaluronic Acid", "Ceramides", "Shea Butter"],
    avoidIngredients: ["Alcohol", "Fragrance"],
    requiredProducts: ["Moisturizer", "Hydrating Serum"],
    avoidProducts: ["Exfoliators", "Clay Masks"],
  },
  {
    caseName: "Sensitive Skin",
    tooltip: "Skin that is easily irritated, red, or reactive to products.",
    requiredIngredients: ["Centella Asiatica", "Aloe Vera", "Panthenol"],
    avoidIngredients: ["Essential Oils", "Alcohol"],
    requiredProducts: ["Soothing Toner", "Barrier Cream"],
    avoidProducts: ["Scrubs", "Strong Acids"],
  },
];

export const masks: Mask[] = [
  {
    id: 1,
    name: "Detox & Calm Mask",
    ingredients: [
      { tag: "charcoal", quantity: 2 },
      { tag: "aloe-vera", quantity: 2 },
      { tag: "tea-tree-oil", quantity: 1 },
    ],
    case: "oily",
    tooltip: "Detoxifies, calms irritation, and reduces acne.",
  },
  {
    id: 2,
    name: "Hydra Glow Mask",
    ingredients: [
      { tag: "hyaluronic-acid", quantity: 3 },
      { tag: "vitamin-c", quantity: 1 },
      { tag: "chamomile", quantity: 1 },
    ],
    case: "dry",
    tooltip: "Deep hydration and glowing skin with calming effects.",
  },
  {
    id: 3,
    name: "Balance Brightening Mask",
    ingredients: [
      { tag: "niacinamide", quantity: 2 },
      { tag: "kaolin-clay", quantity: 2 },
      { tag: "vitamin-c", quantity: 1 },
    ],
    case: "combination",
    tooltip: "Balances oil, brightens complexion, and smooths texture.",
  },
];

export const gameMaskIngredients: MaskIngredient[] = [
  {
    name: "Kaolin Clay",
    tag: "kaolin-clay",
    benefits: ["Absorbs oil", "Cleanses pores"],
    is_allergen: false,
  },
  {
    name: "Tea Tree Oil",
    tag: "tea-tree-oil",
    benefits: ["Reduces acne", "Anti-inflammatory"],
    is_allergen: false,
  },
  {
    name: "Aloe Vera",
    tag: "aloe-vera",
    benefits: ["Soothes skin", "Hydrates"],
    is_allergen: false,
  },
  {
    name: "Niacinamide",
    tag: "niacinamide",
    benefits: ["Improves texture", "Brightens skin"],
    is_allergen: false,
  },
  {
    name: "Charcoal",
    tag: "charcoal",
    benefits: ["Detoxifies", "Draws out impurities"],
    is_allergen: false,
  },
  {
    name: "Hyaluronic Acid",
    tag: "hyaluronic-acid",
    benefits: ["Hydrates", "Plumps skin"],
    is_allergen: false,
  },
  {
    name: "Chamomile Extract",
    tag: "chamomile",
    benefits: ["Calms redness", "Anti-inflammatory"],
    is_allergen: false,
  },
  {
    name: "Vitamin C",
    tag: "vitamin-c",
    benefits: ["Brightens", "Fights free radicals"],
    is_allergen: false,
  },
];
